#!/bin/bash

# Runs whatever inside the vagrant box
function v {
  vagrant ssh -c "sudo -u vcv2 -i -- bash -c 'cd /vcv2 && $*'"
}

# Runs whatever rake task inside the vagrant box
function vr {
  v "rake $*"
}

